name: Global State Recordings
favicon: null
layout_spectrum: 0.98903
typography_spectrum: 0.45959
title: Music For The Discerning Dance Music Lover
author:
  name: Ollie Jaye
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: '707685422641773'
color:
  brandColors:
    - '#000000'
    - '#fffcf6'
    - '#464847'
    - '#d0d0d0'
    - '#9b9b9b'
  brandStrength: 0.08894333033822477
  lightness: 0.6160114405211061
  saturation: 0.4560425023082644
  rhythmicContrast: 0.5603673555888236
purpose: []
