typography_spectrum: 0.45959
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.08894333033822477
  lightness: 0.6160114405211061
  saturation: 0.4560425023082644
  rhythmicContrast: 0.5603673555888236
opengraph:
  image: null
  type: null
  appId: '707685422641773'
layout_spectrum: 0.98903
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Ollie Jaye
name: Global State Recordings
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Music For The Discerning Dance Music Lover
purpose: []
