typography_spectrum: 0.32759
color:
  saturation: 0.4403276217635721
  brandStrength: 0.4325769441202283
  lightness: 0.44689708622172475
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
  rhythmicContrast: 0.14440265856683254
opengraph:
  image: null
  type: null
  appId: '707685422641773'
layout_spectrum: 0.09331604419276118
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Ollie Jaye
name: Global State Recordings
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Music For The Discerning Dance Music Lover
purpose: []
