typography_spectrum: 0.32759
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.25
  lightness: 0.7433414070401341
  saturation: 0.32523649325594306
  rhythmicContrast: 0.02621616260148585
opengraph:
  image: null
  type: null
  appId: '707685422641773'
layout_spectrum: 0.7401161498855799
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Ollie Jaye
name: Global State Recordings
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Music For The Discerning Dance Music Lover
purpose: []
